module.exports = {
    filepath: "./src/",
    arrowParens: 'avoid',
    bracketSpacing: true,
    embeddedLanguageFormatting: 'auto',
    htmlWhitespaceSensitivity: 'css',
    insertPragma: false,
    bracketSameLine: false,
    printWidth: 90,
    proseWrap: 'preserve',
    quoteProps: 'consistent',
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: 'es5',
    useTabs: false,
};
